### ISSUE TITLE
Task to rewrite image tags to image shortcodes

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-assets#167]
## Overview

https://docs.silverstripe.org/en/4/changelogs/4.0.0/#image-shortcode

>  Newly inserted images will automatically receive the shortcode and ownership tracking, and existing <img> will continue to work.

We should provide a mechanism to move from the previous format if we want to remove that legacy handling at some point. There are several implementations of this already: 
* https://gist.github.com/muskie9/8321b9730c191d5c22b14ce2f316a1af
* https://github.com/silverstripe-superchargers/ss4-upgrade-scripts/blob/dcdfe4c494bf29ca23dbbcc708f95fbf1a32c0eb/SS4ContentImageMigration.php

## Acceptance Criteria

- [x] Links to asset files embedded in HTML content through the 3.x CMS (`<a href=assets/file.pdf>`) aren't broken
- [x] Links to original images embedded in HTML content through the 3.x CMS (`<img src=image.png>`) aren't broken
- [x] All images embedded in HTML content through the 3.x CMS are editable through the 4.x CMS UI
- [x] Links to image variants (e.g. resize) embedded in HTML content through the 3.x CMS (`<img src=_resampled/ResizedImage[hash]-image.png>`) aren't broken
- [x] When rewriting links to images variants created through the 3.x CMS, no duplicates of those resized images are created
- [x] Any migration task makes best use of available resources (e.g. reuses existing image variants rather than recreating them, minimises or eliminates duplicate variants)
- [x] Resized images are permalinks (can be linked to directly)
- [x] Any rewrites of HTML necessary for this purpose apply to both draft and published content
- [x] Any rewrites of HTML are not causing new draft versions, or publish drafts (and avoid confusing CMS authors with this system-level task)
- [x] Requires minimal configuration (auto-detects database columns with HTML content)
- [x] Any rewrites of HTML are configurable by developers to fit their particular project (e.g. opt-out of auto-detected database columns)
- [x] If there is a migration task, it can be run via CLI or queuedjobs, and works on installations with 100k+ records
- [x] Running a migration task is not required for operating your website under new SilverStripe releases (although you might encounter some edge cases without it)

## Notes

 * We're aiming to put this into a 4.4 minor release, and temporarily fix broken links in a 4.3 patch release.
 * We're fixing broken links (`assets/[hash]/image.png` instead of `assets/image.png`) through https://github.com/silverstripe/silverstripe-versioned/issues/177. This task might rely on the bugfix implemented here.
 * Both moving and recreating image variants assumes you can get all the metadata required from the file name, either to rename it into the new image variant file name format, or to recreate it via the asset abstraction layer
 * We're allowing sync of filesystem and database state through https://github.com/silverstripe/silverstripe-assets/issues/175
 * Excludes rewriting historical versions

## Example Structure

```
3.x

assets/
	file.png
	_resampled/ResizedImage400x3020-file.png

<img src="_resampled/ResizedImage400x200-file.png" />

4.0

assets/
	[file-hash]
		file.png
		file-ResizedImage400x200.png <- duplicate
	_resampled/ResizedImage400x200-file.png <- broken association
	[new-file-hash]
		new-file.png
		new-file-ResizedImage[variant-hash].png
	.protected/
		[private-file-hash]
			private-file.png

<img src="_resampled/ResizedImage400x200-file.png" />
[image id="-- id for [file-hash]/file-ResizedImage400x200.png --"]

4.4

assets/
	file.png
	file-ResizedImage400x3020.png
	new-file.png
	new-file-ResizedImage[variant-hash].png
	.protected/
		[private-file-hash]
			private-file.png

[image id="-- id for file-ResizedImage400x3020.png --"]
[image id="-- id for new-file-ResizedImage400x200.png --"]
```

## Tasks
- [x] Implement task
    - [x] Find DOM parser library, prefer this over regex
    - [x] Iterate over all DataObject HTMLText columns
        - [x] Look for image tags with href referencing assets
        - [x] rewrite href to use shortcode
- [x] Write unit tests
- [x] Add to documentation - as a part of upgrader

## Pull Requests
- [x] https://github.com/silverstripe/silverstripe-framework/pull/8892 for listing fields on classes and adding documentation to upgrading guide
- [ ] https://github.com/silverstripe/silverstripe-assets/pull/227 - the task
- [x] https://github.com/silverstripe/silverstripe-framework/pull/8960

**Comment by robbieaverill** [comment]
PR at #168 for review

**Comment by chillu** [comment]
There's a fun edge case existing in the 3.x to 4.x migration. If you embedded an image in HTML content in the 3.x CMS, and the CMS determined it needed an auto-generated resize, then you'll end up with a duplicate file. That file is "associated" to the original by naming convention (`assets/image.png` becomes `assets/_resampled/ResizedImage[variant-hash]-image.png`). 4.x formalises this further through "image variants", which follow a different naming convention (`assets/[hash]/image__ResizedImage[variant-hash].png`). Through the file migration task, `assets/image.png` is moved to `assets/[hash]/image.png`. New image variants are created *in addition* to the old ones, so you'll end up with an orphaned variant at `assets/[hash]/image__ResizedImage[variant-hash].png` which is still actively referenced in HTML content. There's currently no way to remedy this other than manually replacing the image through the CMS editing UI (or running the task proposed at https://github.com/silverstripe/silverstripe-assets/issues/167).

We're looking to remove orphaned files through https://github.com/silverstripe/silverstripe-assets/issues/175, which would also remove those variants, and break those links. So technically, we would require you to have run this image shortcode migration task *before* removing orphaned files.

**Comment by bergice** [comment]
@maxime-rainville this is ready for review, but will be blocked until the file helper classes are ready.
