### ISSUE TITLE
File Migration Tasks confuses 10-char-long folders for hash folder

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-assets#269]
If you are migrating a file such as `multimedia/video.mp4`, the file migration script will get confused and think that `multimedia` is the hash for `video.mp4`.

# Subtasks
* [x] Update `HashFileIDHelper` to only accept hexa-decimal character in the hash folder
* [x] Update file resolution mechanism to validate that file matches hash ... this may be opening a can of worms as it might require us to read the entire file every time we serve it to make sure its actual hash matches the expected hash
* [x] Look back at the rest of the uni test and add some extra edge cases to cover ambiguous folder names.

# Parent PR
* https://github.com/silverstripe/silverstripe-assets/pull/274

**Comment by maxime-rainville** [comment]
The changes introduce by https://github.com/silverstripe/silverstripe-assets/pull/267 will completely negated this issue for SS3 migration. When migrating SS3 files, the FileMigrationHelper will only use the LegacyFileIDHelper now.

I'll add an extra bit of logic to make sure SS4.3 to SS4.4 migration works as well.

**Comment by bergice** [comment]
Can confirm this works.
