### ISSUE TITLE
Ensure that S3 module works with asset abstraction

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-assets#42]
## Acceptance Criteria

 * I can upload files to S3 from the assets area
 * I can upload list files from S3 in the assets area (draft and live)
 * I can preview draft images on my website hosted on S3
 * I can see live images on my website hosted on S3

## Notes

 * Existing module: https://github.com/madmatt/silverstripe-s3

## Excludes

 * Making this work well in the asset admin UX, see https://github.com/silverstripe/silverstripe-framework/issues/5544
 
# Tasks

 - [x] Setup aws test site with s3 module
 - [x] Update module for 4.0.0-beta1
 - [x] Optimise performance issues broken out into (https://github.com/silverstripe/silverstripe-assets/issues/43)
 
# PR

 - [x] https://github.com/madmatt/silverstripe-s3/pull/5

**Comment by chillu** [comment]
@tractorcow @flamerohr Can one of you please check how much work there's left to get the module working so we can size this next week? If you need an S3 bucket to test, just sign up for a free personal AWS account.

**Comment by tractorcow** [comment]
Implementation works; Performance considerations still need to be addressed in https://github.com/silverstripe/silverstripe-assets/issues/43 though.
