### ISSUE TITLE
S3 Support

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-assets#52]
Placeholder for work we are currently doing to improve performance of this module on AWS s3.

# Internal jira stories

 - [ ] https://silverstripe.atlassian.net/browse/AWSMP-686 (Persistent user cache for SilverStripe Platform environments)
 - [ ] https://silverstripe.atlassian.net/browse/AWSMP-698 (S3 support for SS4 on SSP)
 - [ ] https://silverstripe.atlassian.net/browse/AWSMP-692 (SS4 draft assets + SS3 performant 404s)

# Architecture

 - We want to design and implement an s3 asset store based on the existing local filesystem architecture. However, as s3 has some very specific performance concerns, and additional security features, certain parts of the framework and asset backend need to be customised.
  - The intention is to retain the abstract FlysystemAssetStore, and the twin protected / public asset adapter model, but customise the adapters used to be s3 based backends.
  - Initial performance testing shows that streaming s3 content directly though silverstripe is extremely inefficient, and in it's place we can use a combination of s3/cloudfront signed protected urls. These are time-limited urls that allow public access to private files.
  - For s3 we will remove the session-based grant permission system, along with any references to protected file controller.
  - A multi-level caching system is necessary for minimising API calls to s3.
  - Similarly, a logging backend (can be applied over the top of the s3 adaptor) should be available for logging of these calls, so we can measure performance of each silverstripe request.
  - metadata will need to be cached in such a way that it's consistent across a multi-server environment. For instance ->has() calls should be cached in a safe and consistent way that avoids outdated false positives. We are looking at either dynamodb, or mysql as a caching store for this.
  - Metadata will need to be exported with asset snapshots, and imported with these snapshots, in order to avoid massive cache-miss surges on restore.
  - Redundant API calls will need to be minimised. E.g. a `does exist` and `get metadata` could be performed in a single API call, and the single result used for both. Another example is redundant ->has() calls on the main variant and subsequently the thumbnail variant, when we only need to perform this check on the thumbnail.

# Tasks

 - [ ] Implement cloudfront protected signed asset urls (https://github.com/silverstripe/silverstripe-s3/issues/12)
 - [ ] Implement s3 protected signed asset urls 
 - [x] Shift github.com/madmatt/silverstripe-s3 to silverstripe vendor
 - [ ] Disable inline-thumbnails for asset-admin thumbnails when using s3 assets
 - [ ] Get NFR for 50 protected thumbnails per page down to 10 seconds or less (aim to start loading thumbnails at 5 seconds).

**Comment by sminnee** [comment]
Once you have more clarity, the description of this card should be updated to include some detail of the challenges you need to overcome and infrastructure architecture to provide this.

**Comment by chillu** [comment]
Closing this - we nominally have S3 support now. Remaining issues are tracked in https://github.com/silverstripe/silverstripe-s3/issues
