### ISSUE TITLE
Add deprecation messages in FlysystemAssetStore

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-assets#521]
**This is currently blocking https://github.com/silverstripe/silverstripe-assets/pull/522**

There are a bunch of `@deprecated 1.4.0` phpdoc's on methods in [FlysystemAssetStore](https://github.com/silverstripe/silverstripe-assets/blob/1/src/Flysystem/FlysystemAssetStore.php)

As part of https://github.com/silverstripe/silverstripe-framework/issues/10531, we need to add standardized message to all phpdocs. i.e.

`     * @deprecated 1.4.0 My message`

Use either of the following standardized messages:
- `Use <methodname>() instead`
- `Will be removed without equivalent functionality to replace it`

### Acceptance criteria
- [x] All `@deprecated` phpdoc's in FlystemAssetStore with missing messages have message added

### Pull request
- [x] https://github.com/silverstripe/silverstripe-framework/pull/10556
- [x] https://github.com/silverstripe/silverstripe-assets/pull/525
- [x] https://github.com/silverstripe/developer-docs/pull/107

**Comment by maxime-rainville** [comment]
## What's been deprecated, why and what the alternative is (if any)

### Legacy filename

Prior to the 4.4 release, there was something called legacy filename that would allow you to output filename without the hash. That was completely busted and become redundant once we enable NaturalFileIDs. We kept some of the methods around because they were part of the API but they effectively do nothing now.

These should be deprecated and throw warning from now on.

https://github.com/silverstripe/silverstripe-assets/blob/ce9464b6282c34e37324987ea2dd74cae89c50ca/src/Flysystem/FlysystemAssetStore.php#L88

https://github.com/silverstripe/silverstripe-assets/blob/ce9464b6282c34e37324987ea2dd74cae89c50ca/src/Flysystem/FlysystemAssetStore.php#L1226-L1229

### Methods that became part of the FileID helpers
Asset Store used to be very directive because it would assume that all the files would be contained hashes. Those methods were moved to file ID helpers. But some hackish implementation were kept on the asset store ... because SEMVER.

These methods should throw warnings now and be removed altogether.

https://github.com/silverstripe/silverstripe-assets/blob/ce9464b6282c34e37324987ea2dd74cae89c50ca/src/Flysystem/FlysystemAssetStore.php#L262

https://github.com/silverstripe/silverstripe-assets/blob/ce9464b6282c34e37324987ea2dd74cae89c50ca/src/Flysystem/FlysystemAssetStore.php#L708

https://github.com/silverstripe/silverstripe-assets/blob/ce9464b6282c34e37324987ea2dd74cae89c50ca/src/Flysystem/FlysystemAssetStore.php#L914

https://github.com/silverstripe/silverstripe-assets/blob/ce9464b6282c34e37324987ea2dd74cae89c50ca/src/Flysystem/FlysystemAssetStore.php#L1061

https://github.com/silverstripe/silverstripe-assets/blob/ce9464b6282c34e37324987ea2dd74cae89c50ca/src/Flysystem/FlysystemAssetStore.php#L1353

https://github.com/silverstripe/silverstripe-assets/blob/ce9464b6282c34e37324987ea2dd74cae89c50ca/src/Flysystem/FlysystemAssetStore.php#L1367

https://github.com/silverstripe/silverstripe-assets/blob/ce9464b6282c34e37324987ea2dd74cae89c50ca/src/Flysystem/FlysystemAssetStore.php#L1381

https://github.com/silverstripe/silverstripe-assets/blob/ce9464b6282c34e37324987ea2dd74cae89c50ca/src/Flysystem/FlysystemAssetStore.php#L1394

https://github.com/silverstripe/silverstripe-assets/blob/ce9464b6282c34e37324987ea2dd74cae89c50ca/src/Flysystem/FlysystemAssetStore.php#L1407

#### This method is not currently marked as deprecated, but should be.

https://github.com/silverstripe/silverstripe-assets/blob/ce9464b6282c34e37324987ea2dd74cae89c50ca/src/Flysystem/FlysystemAssetStore.php#L772

### Task that need to be removed

These task are no longer needed and should be deprecated/removed

- [FixFolderPermissionsHelper.php](https://github.com/silverstripe/silverstripe-assets/blob/1/src/Dev/FixFolderPermissionsHelper.php)
- [VersionedFilesMigrator.php](https://github.com/silverstripe/silverstripe-assets/blob/1/src/Dev/VersionedFilesMigrator.php)
- [FileMigrationHelper.php](https://github.com/silverstripe/silverstripe-assets/blob/1/src/Dev/Tasks/FileMigrationHelper.php)
- [FolderMigrationHelper.php](https://github.com/silverstripe/silverstripe-assets/blob/1/src/Dev/Tasks/FolderMigrationHelper.php)
- [LegacyThumbnailMigrationHelper.php](https://github.com/silverstripe/silverstripe-assets/blob/1/src/Dev/Tasks/LegacyThumbnailMigrationHelper.php)
- [NormaliseAccessMigrationHelper.php](https://github.com/silverstripe/silverstripe-assets/blob/1/src/Dev/Tasks/NormaliseAccessMigrationHelper.php)
- [SecureAssetsMigrationHelper.php](https://github.com/silverstripe/silverstripe-assets/blob/1/src/Dev/Tasks/SecureAssetsMigrationHelper.php)
- [TagsToShortcodeHelper.php](https://github.com/silverstripe/silverstripe-assets/blob/1/src/Dev/Tasks/TagsToShortcodeHelper.php)
- [TagsToShortcodeTask.php](https://github.com/silverstripe/silverstripe-assets/blob/1/src/Dev/Tasks/TagsToShortcodeTask.php)
- [VersionedFilesMigrationTask.php](https://github.com/silverstripe/silverstripe-assets/blob/1/src/Dev/Tasks/VersionedFilesMigrationTask.php)

### Legacy File resolution

To be able to migrate and resolve SS3 file URLs, we had to create a lot of of legacy abstraction (aka replicating the SS3 file resolution logic in SS4).

That legacy logic is no longer needed.

This class should be deprecated: [LegacyFileIDHelper.php](https://github.com/silverstripe/silverstripe-assets/blob/1/src/FilenameParsing/LegacyFileIDHelper.php)

This bit of config can be simplified in CMS5:

- `FileResolutionStrategy.public` should only use `NaturalFileIDHelper`
- `FileResolutionStrategy.protected` should only use `HashFileIDHelper`

This will however mean that everyone who wants to upgrade to CMS5 and had a site created prior to CMS4.4 will have to had run the FileMigrationHelper at some point.

https://github.com/silverstripe/silverstripe-assets/blob/ce9464b6282c34e37324987ea2dd74cae89c50ca/_config/asset.yml#L26-L43

### Scope creep to annoy @emteknetnz 

In CMS4.4, I introduced [ParsedFileID](https://github.com/silverstripe/silverstripe-assets/blob/1/src/FilenameParsing/ParsedFileID.php). Until then, we would use `tuple` which were essentially arrays with a `filename`, `hash` and `variant` keys.

`ParsedFileID` contains all of that, but in a class with types for everything. We should replace any reference to `tuple` with a `ParsedFileID`.

### Even more scope creep
Flysystem's `Filesystem` object implements the `FilesystemOperator`. I think everywhere we expect a `Filesystem` we could just as easily expect a `FilesystemOperator`. 

This would open some possibilities for some people https://github.com/silverstripe/silverstripe-assets/issues/368

**Comment by maxime-rainville** [comment]
This PR will handle the deprecations: https://github.com/silverstripe/silverstripe-assets/pull/525

I'll spin up my other side concerns into their own card.

**Comment by GuySartorelli** [comment]
@max please create a PR for the 4.12.0 changelog for the things that are being newly deprecated.

**Comment by GuySartorelli** [comment]
This is all done
